// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	api "github.com/weaviate/weaviate-cloud/internal/api"

	mock "github.com/stretchr/testify/mock"
)

// MockAPIClient is an autogenerated mock type for the APIClient type
type MockAPIClient struct {
	mock.Mock
}

type MockAPIClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIClient) EXPECT() *MockAPIClient_Expecter {
	return &MockAPIClient_Expecter{mock: &_m.Mock}
}

// CreateCluster provides a mock function with given fields: ctx, req, opts
func (_m *MockAPIClient) CreateCluster(ctx context.Context, req api.CreateClusterRequest, opts api.CreateClusterOptions) (*api.Cluster, error) {
	ret := _m.Called(ctx, req, opts)

	if len(ret) == 0 {
		panic("no return value specified for CreateCluster")
	}

	var r0 *api.Cluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, api.CreateClusterRequest, api.CreateClusterOptions) (*api.Cluster, error)); ok {
		return rf(ctx, req, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, api.CreateClusterRequest, api.CreateClusterOptions) *api.Cluster); ok {
		r0 = rf(ctx, req, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Cluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, api.CreateClusterRequest, api.CreateClusterOptions) error); ok {
		r1 = rf(ctx, req, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPIClient_CreateCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCluster'
type MockAPIClient_CreateCluster_Call struct {
	*mock.Call
}

// CreateCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - req api.CreateClusterRequest
//   - opts api.CreateClusterOptions
func (_e *MockAPIClient_Expecter) CreateCluster(ctx interface{}, req interface{}, opts interface{}) *MockAPIClient_CreateCluster_Call {
	return &MockAPIClient_CreateCluster_Call{Call: _e.mock.On("CreateCluster", ctx, req, opts)}
}

func (_c *MockAPIClient_CreateCluster_Call) Run(run func(ctx context.Context, req api.CreateClusterRequest, opts api.CreateClusterOptions)) *MockAPIClient_CreateCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(api.CreateClusterRequest), args[2].(api.CreateClusterOptions))
	})
	return _c
}

func (_c *MockAPIClient_CreateCluster_Call) Return(_a0 *api.Cluster, _a1 error) *MockAPIClient_CreateCluster_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPIClient_CreateCluster_Call) RunAndReturn(run func(context.Context, api.CreateClusterRequest, api.CreateClusterOptions) (*api.Cluster, error)) *MockAPIClient_CreateCluster_Call {
	_c.Call.Return(run)
	return _c
}

// GetCluster provides a mock function with given fields: ctx, id
func (_m *MockAPIClient) GetCluster(ctx context.Context, id string) (*api.Cluster, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCluster")
	}

	var r0 *api.Cluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*api.Cluster, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *api.Cluster); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Cluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPIClient_GetCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCluster'
type MockAPIClient_GetCluster_Call struct {
	*mock.Call
}

// GetCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAPIClient_Expecter) GetCluster(ctx interface{}, id interface{}) *MockAPIClient_GetCluster_Call {
	return &MockAPIClient_GetCluster_Call{Call: _e.mock.On("GetCluster", ctx, id)}
}

func (_c *MockAPIClient_GetCluster_Call) Run(run func(ctx context.Context, id string)) *MockAPIClient_GetCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAPIClient_GetCluster_Call) Return(_a0 *api.Cluster, _a1 error) *MockAPIClient_GetCluster_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPIClient_GetCluster_Call) RunAndReturn(run func(context.Context, string) (*api.Cluster, error)) *MockAPIClient_GetCluster_Call {
	_c.Call.Return(run)
	return _c
}

// GetClusterStatus provides a mock function with given fields: ctx, id
func (_m *MockAPIClient) GetClusterStatus(ctx context.Context, id string) (api.ClusterStatus, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetClusterStatus")
	}

	var r0 api.ClusterStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (api.ClusterStatus, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) api.ClusterStatus); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(api.ClusterStatus)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPIClient_GetClusterStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClusterStatus'
type MockAPIClient_GetClusterStatus_Call struct {
	*mock.Call
}

// GetClusterStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAPIClient_Expecter) GetClusterStatus(ctx interface{}, id interface{}) *MockAPIClient_GetClusterStatus_Call {
	return &MockAPIClient_GetClusterStatus_Call{Call: _e.mock.On("GetClusterStatus", ctx, id)}
}

func (_c *MockAPIClient_GetClusterStatus_Call) Run(run func(ctx context.Context, id string)) *MockAPIClient_GetClusterStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAPIClient_GetClusterStatus_Call) Return(_a0 api.ClusterStatus, _a1 error) *MockAPIClient_GetClusterStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPIClient_GetClusterStatus_Call) RunAndReturn(run func(context.Context, string) (api.ClusterStatus, error)) *MockAPIClient_GetClusterStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ListClusters provides a mock function with given fields: ctx
func (_m *MockAPIClient) ListClusters(ctx context.Context) ([]api.Cluster, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListClusters")
	}

	var r0 []api.Cluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]api.Cluster, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []api.Cluster); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]api.Cluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPIClient_ListClusters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClusters'
type MockAPIClient_ListClusters_Call struct {
	*mock.Call
}

// ListClusters is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAPIClient_Expecter) ListClusters(ctx interface{}) *MockAPIClient_ListClusters_Call {
	return &MockAPIClient_ListClusters_Call{Call: _e.mock.On("ListClusters", ctx)}
}

func (_c *MockAPIClient_ListClusters_Call) Run(run func(ctx context.Context)) *MockAPIClient_ListClusters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAPIClient_ListClusters_Call) Return(_a0 []api.Cluster, _a1 error) *MockAPIClient_ListClusters_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPIClient_ListClusters_Call) RunAndReturn(run func(context.Context) ([]api.Cluster, error)) *MockAPIClient_ListClusters_Call {
	_c.Call.Return(run)
	return _c
}

// ListRegions provides a mock function with given fields: ctx
func (_m *MockAPIClient) ListRegions(ctx context.Context) ([]api.Region, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRegions")
	}

	var r0 []api.Region
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]api.Region, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []api.Region); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]api.Region)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPIClient_ListRegions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRegions'
type MockAPIClient_ListRegions_Call struct {
	*mock.Call
}

// ListRegions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAPIClient_Expecter) ListRegions(ctx interface{}) *MockAPIClient_ListRegions_Call {
	return &MockAPIClient_ListRegions_Call{Call: _e.mock.On("ListRegions", ctx)}
}

func (_c *MockAPIClient_ListRegions_Call) Run(run func(ctx context.Context)) *MockAPIClient_ListRegions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAPIClient_ListRegions_Call) Return(_a0 []api.Region, _a1 error) *MockAPIClient_ListRegions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPIClient_ListRegions_Call) RunAndReturn(run func(context.Context) ([]api.Region, error)) *MockAPIClient_ListRegions_Call {
	_c.Call.Return(run)
	return _c
}

// Whoami provides a mock function with given fields: ctx
func (_m *MockAPIClient) Whoami(ctx context.Context) (*api.WhoAmI, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Whoami")
	}

	var r0 *api.WhoAmI
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*api.WhoAmI, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *api.WhoAmI); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.WhoAmI)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPIClient_Whoami_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Whoami'
type MockAPIClient_Whoami_Call struct {
	*mock.Call
}

// Whoami is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAPIClient_Expecter) Whoami(ctx interface{}) *MockAPIClient_Whoami_Call {
	return &MockAPIClient_Whoami_Call{Call: _e.mock.On("Whoami", ctx)}
}

func (_c *MockAPIClient_Whoami_Call) Run(run func(ctx context.Context)) *MockAPIClient_Whoami_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAPIClient_Whoami_Call) Return(_a0 *api.WhoAmI, _a1 error) *MockAPIClient_Whoami_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPIClient_Whoami_Call) RunAndReturn(run func(context.Context) (*api.WhoAmI, error)) *MockAPIClient_Whoami_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAPIClient creates a new instance of MockAPIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIClient {
	mock := &MockAPIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
